# ==============================================================================
# SGHospitalizacion01 - Configuración para Docker
# ==============================================================================
spring.application.name=SGHospitalizacion

# Configuración del Datasource MongoDB en red Docker (sghospitalizacion_net)
spring.mongodb.uri=mongodb://mongo_sg_hospitalizacion:27017/sg_hospitalizacion
spring.data.mongodb.uri=mongodb://mongo_sg_hospitalizacion:27017/sg_hospitalizacion
spring.data.mongodb.auto-index-creation=true

# Servidor
server.address=0.0.0.0
server.port=8080

# Seguridad JWT (Clave Base64 HMAC-SHA256 - mínimo 256 bits)
JWT_SECRET=MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=

# Sistema Base Externo (SGBITAMEDICA03)
sgbitamedica.base-url=${SGBITAMEDICA_URL:http://host.docker.internal:8084}

# Logs
logging.level.com.ug.ec=INFO
logging.level.org.springframework.mongodb=INFO
logging.level.org.springframework.data.mongodb=INFO
